image:
  - Visual Studio 2022
  - Visual Studio 2019
  - Visual Studio 2017
  - Visual Studio 2015
  - Visual Studio 2013

install:
  # Install MS-MPI
  - ps: Start-FileDownload 'https://download.microsoft.com/download/A/E/0/AE002626-9D9D-448D-8197-1EA510E297CE/msmpisetup.exe'
  - MSMpiSetup.exe -unattend -full
  # Install MS-MPI SDK
  - ps: Start-FileDownload 'https://download.microsoft.com/download/A/E/0/AE002626-9D9D-448D-8197-1EA510E297CE/msmpisdk.msi'
  - msmpisdk.msi /passive

  - set MSMPI_BIN=C:\Program Files\Microsoft MPI\Bin\
  - set MSMPI_INC=C:\Program Files (x86)\Microsoft SDKs\MPI\Include\
  - set MSMPI_LIB32=C:\Program Files (x86)\Microsoft SDKs\MPI\Lib\x86\
  - set MSMPI_LIB64=C:\Program Files (x86)\Microsoft SDKs\MPI\Lib\x64\
  - set MSMPI
  - set PATH=C:\Program Files\Microsoft MPI\Bin;%PATH%

build_script:
  - cmake --version
  - mkdir build && cd build
  - cmake ..
  - cmake --build . --config Release

test_script:
  - ctest -V -C Release
