image:
  - Visual Studio 2022
  - Visual Studio 2019
  - Visual Studio 2017
  - Visual Studio 2015
  - Visual Studio 2013

install:
  - ps: |
      $rooturl="https://github.com/microsoft/Microsoft-MPI/releases/download"
      $version="10.1.1"
      $baseurl="$rooturl/v$version"
  # Install MS-MPI
  - ps: Start-FileDownload "$baseurl/msmpisetup.exe"
  - MSMpiSetup.exe -unattend
  # Install MS-MPI SDK
  - ps: Start-FileDownload "$baseurl/msmpisdk.msi"
  - msmpisdk.msi /passive /qn

  - set MSMPI_BIN=C:\Program Files\Microsoft MPI\Bin\
  - set MSMPI_INC=C:\Program Files (x86)\Microsoft SDKs\MPI\Include\
  - set MSMPI_LIB32=C:\Program Files (x86)\Microsoft SDKs\MPI\Lib\x86\
  - set MSMPI_LIB64=C:\Program Files (x86)\Microsoft SDKs\MPI\Lib\x64\
  - set MSMPI
  - set PATH=C:\Program Files\Microsoft MPI\Bin;%PATH%

build_script:
  - cmake --version
  - mkdir build && cd build
  - cmake ..
  - cmake --build . --config Release

test_script:
  - ctest -V -C Release
