language: cpp
dist: trusty
sudo: required

script:
  - mpirun --version
  - mkdir build
  - cd build
  - cmake -D CMAKE_BUILD_TYPE=Release ..
  - make
  - ctest

matrix:
  include:
    - os: linux
      before_install:
        - sudo sed -i 's/trusty/zesty/g' /etc/apt/sources.list
        - sudo apt-get update -y
        - sudo apt-get install libopenmpi-dev openmpi-bin
    - os: osx
      osx_image: xcode9.2
      before_install:
        - brew update
        - brew cask uninstall oclint
        - brew install open-mpi
        - export EXTRAFLAG=--oversubscribe
    - os: linux
      before_install:
        - sudo sed -i 's/trusty/zesty/g' /etc/apt/sources.list
        - sudo apt-get update -y
        - sudo apt-get install libmpich-dev mpich
    - os: osx
      osx_image: xcode9.2
      before_install:
        - brew update
        - brew cask uninstall oclint
        - brew install mpich