language: cpp
dist: xenial
sudo: required

script:
  - mpirun --version
  - cmake --version
  - mkdir build
  - cd build
  - cmake -D CMAKE_BUILD_TYPE=Release ..
  - make
  - ctest -V

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - libopenmpi-dev openmpi-bin
    - os: osx
      osx_image: xcode10
      before_install:
        - brew cask uninstall oclint
      install:
        - brew install open-mpi
      env:
        - EXTRA_FLAG=--oversubscribe
    - os: linux
      addons:
        apt:
          packages:
            - libmpich-dev mpich
    - os: osx
      osx_image: xcode10
      before_install:
        - brew cask uninstall oclint
      install:
        - brew install mpich
