language: cpp
dist: xenial

script:
  - mpirun --version
  - cmake --version
  - mkdir build
  - cd build
  - cmake -D CMAKE_BUILD_TYPE=Release ..
  - make
  - ctest -V

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - libopenmpi-dev openmpi-bin
      env:
        - ==OPENMPI==
    - os: osx
      osx_image: xcode10.1
      addons:
        homebrew:
          packages:
            - open-mpi
      env:
        - ==OPENMPI==
        - EXTRA_FLAG=--oversubscribe
    - os: linux
      addons:
        apt:
          packages:
            - libmpich-dev mpich
      env:
        - ==MPICH==
    - os: osx
      osx_image: xcode10.1
      addons:
        homebrew:
          packages:
            - mpich
      env:
        - ==MPICH==
