language: cpp
sudo: required
dist: trusty

before_install:
  - test -n $CC && unset CC
  - test -n $CXX && unset CXX

script:
  - mkdir build
  - cd build
  - cmake .. && make
  - ctest

matrix:
  include:
    - os: linux
      addons:
       apt:
        packages:
         - libopenmpi-dev
         - openmpi-bin
    - os: osx
      osx_image: xcode8.2
      before_install:
        - brew update
        - brew cask uninstall oclint
        - brew install open-mpi
        - brew install cmake
