language: cpp
dist: trusty
sudo: required

before_install:
  - test -n $CC && unset CC
  - test -n $CXX && unset CXX

script:
  - mkdir build
  - cd build
  - cmake -D CMAKE_BUILD_TYPE=Release ..
  - make
  - ctest

matrix:
  include:
    - os: linux
      addons:
       apt:
        packages:
         - libopenmpi-dev
         - openmpi-bin
    - os: osx
      osx_image: xcode9.2
      before_install:
        - brew update
        - brew cask uninstall oclint
        - brew install open-mpi
