language: cpp
dist: trusty
sudo: required

script:
  - mpirun --version
  - mkdir build
  - cd build
  - cmake -D CMAKE_BUILD_TYPE=Release ..
  - make
  - ctest -V

matrix:
  include:
    - os: linux
      before_install:
        - sudo apt-get install libopenmpi-dev openmpi-bin
    - os: osx
      osx_image: xcode9.3
      before_install:
        - brew update
        - brew cask uninstall oclint
        - brew install open-mpi
        - export EXTRA_FLAG=--oversubscribe
    - os: linux
      before_install:
        - sudo apt-get install libmpich-dev mpich
    - os: osx
      osx_image: xcode9.3
      before_install:
        - brew update
        - brew cask uninstall oclint
        - brew install mpich