language: cpp
dist: xenial

script:
  - mpirun --version
  - cmake --version
  - mkdir build
  - cd build
  - cmake -D CMAKE_BUILD_TYPE=Release ..
  - make
  - ctest -V

matrix:
  include:
    - name: Linux ==OPENMPI==
      os: linux
      addons:
        apt:
          packages:
            - libopenmpi-dev openmpi-bin
      env:
      - EXTRA_FLAG=--oversubscribe
    - name: MacOS ==OPENMPI==
      os: osx
      osx_image: xcode10.1
      addons:
        homebrew:
          packages:
            - open-mpi
      env:
        - EXTRA_FLAG=--oversubscribe
    - name: Linux ==MPICH==
      os: linux
      addons:
        apt:
          packages:
            - libmpich-dev mpich
    - name: MacOS ==MPICH==
      os: osx
      osx_image: xcode10.1
      addons:
        homebrew:
          packages:
            - mpich
