language: cpp
sudo: required
dist: trusty
os:
  - linux
  - osx

addons:
 apt:
  packages:
   - libopenmpi-dev
   - openmpi-bin
before_install:
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install open-mpi; fi

env:
  - CMAKE_CXX_COMPILER=mpic++

script:
  - mkdir build
  - cd build
  - cmake .. && make
  - mpirun -n 4 cp-is-fun < ../InputTests/6
