image:
  - Visual Studio 2017
  - Visual Studio 2015
  - Visual Studio 2013

install:
  # Install a recent CMake
  - choco upgrade cmake
  - set path=C:\Program Files\CMake\bin;%path%
  - cmake --version

  # Install MS-MPI
  - ps: Start-FileDownload 'https://download.microsoft.com/download/9/E/D/9ED82A62-4235-4003-A59A-9F6246073F2E/MSMpiSetup.exe'
  - MSMpiSetup.exe -unattend -full
  # Install MS-MPI SDK
  - ps: Start-FileDownload 'https://download.microsoft.com/download/9/E/D/9ED82A62-4235-4003-A59A-9F6246073F2E/msmpisdk.msi'
  - msmpisdk.msi /passive

  - set MSMPI_BIN=C:\Program Files\Microsoft MPI\Bin\
  - set MSMPI_INC=C:\Program Files (x86)\Microsoft SDKs\MPI\Include\
  - set MSMPI_LIB32=C:\Program Files (x86)\Microsoft SDKs\MPI\Lib\x86\
  - set MSMPI_LIB64=C:\Program Files (x86)\Microsoft SDKs\MPI\Lib\x64\

  - set PATH=C:\Program Files\Microsoft MPI\Bin;%PATH%

build_script:
  - set MSMPI
  - mkdir build && cd build
  - cmake ..
  - cmake --build . --config Release

test_script:
  - ctest -V -C Release
